package net.mcreator.mineraisecond.procedure;

import net.minecraft.util.text.TextComponentString;
import net.minecraft.potion.PotionEffect;
import net.minecraft.init.MobEffects;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.Entity;

import net.mcreator.mineraisecond.ElementsClubInfoMod;

import java.util.Map;

@ElementsClubInfoMod.ModElement.Tag
public class ProcedureCHHHHHEEEEEEEEEEEAAAAAAAAAAAAATTTTTTTTTTTPotionStartedapplied extends ElementsClubInfoMod.ModElement {
	public ProcedureCHHHHHEEEEEEEEEEEAAAAAAAAAAAAATTTTTTTTTTTPotionStartedapplied(ElementsClubInfoMod instance) {
		super(instance, 67);
	}

	public static void executeProcedure(Map<String, Object> dependencies) {
		if (dependencies.get("entity") == null) {
			System.err.println("Failed to load dependency entity for procedure CHHHHHEEEEEEEEEEEAAAAAAAAAAAAATTTTTTTTTTTPotionStartedapplied!");
			return;
		}
		Entity entity = (Entity) dependencies.get("entity");
		if (entity instanceof EntityPlayer)
			((EntityPlayer) entity).addExperienceLevel((int) 1000);
		if (entity instanceof EntityPlayer && !entity.world.isRemote) {
			((EntityPlayer) entity).sendStatusMessage(new TextComponentString(
					"Glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou"),
					(false));
		}
		if (entity instanceof EntityLivingBase)
			((EntityLivingBase) entity).addPotionEffect(new PotionEffect(MobEffects.SPEED, (int) 60, (int) 100, (true), (true)));
		if (entity instanceof EntityLivingBase)
			((EntityLivingBase) entity).addPotionEffect(new PotionEffect(MobEffects.STRENGTH, (int) 60, (int) 100, (true), (true)));
		if (entity instanceof EntityLivingBase)
			((EntityLivingBase) entity).addPotionEffect(new PotionEffect(MobEffects.REGENERATION, (int) 60, (int) 100, (true), (true)));
		if (entity instanceof EntityLivingBase)
			((EntityLivingBase) entity).addPotionEffect(new PotionEffect(MobEffects.RESISTANCE, (int) 60, (int) 100, (true), (true)));
	}
}
